[book]
authors = ["Tim McNamara"]
language = "en"
multilingual = false
src = "src"
title = "Build your first web app written in Rust"

[rust]
edition = "2021"

[output.html]
# git-repository-url = "https://github.com/timClicks/talks"
smart-punctuation = true
additional-js = ["hide-menu.js", "slides.js"]
additional-css = ["slides.css"]
#print = false

[output.html.playground]
editable = true