[book]
authors = ["Tim McNamara"]
language = "en"
multilingual = false
src = "src"
title = "Build your first web app written in Rust"

[rust]
edition = "2021"

[output.html]
# git-repository-url = "https://github.com/timClicks/talks"
smart-punctuation = true
additional-js = ["hide-menu.js", "slides.js", ]
additional-css = ["slides.css", ]
#print = false
mathjax-support = true

# TODO: investigate speaker notes. they currently don't work nicely with slides.
# TODO: "speaker-notes/speaker-notes.js"
# TODO: "speaker-notes/speaker-notes.css"

[output.html.playground]
editable = true

